<a href="https://colab.research.google.com/github/snpsuen/Deep_Learning_Data/blob/main/script/pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd

In [4]:
# Initializing the nested list with Data set
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

# creating a pandas dataframe
df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print("df = ")
print(df) # data frame before slicing
print("df.shape = ", df.shape) # data frame before slicing
print("df.iloc[1,2] = ", df.iloc[1,2])
print("df.iloc[1:4, -1] = ")
print(df.iloc[1:4, -1])
print("df.iloc[1:4, -1].shape = ", df.iloc[1:4, -1].shape)
print("df[\"Weight\"] = ")
print(df["Weight"])
print("df[\"Weight\"].shape = ", df["Weight"].shape)
print("df.loc[5] = ")
print(df.loc[5])
print("df.loc[5].shape = ", df.loc[5].shape)
print("df.loc[1:5] = ")
print(df.loc[1:5])
print("df.loc[1:5].shape = ", df.loc[1:5].shape)
df_weight = df["Weight"].values.reshape(-1, 1)
print("df_weight type = ", type(df_weight.shape))
print("df_weight.shape = ", df_weight.shape)
print("df_weight = ")
print(df_weight)

df = 
            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000
df.shape =  (7, 4)
df.iloc[1,2] =  74
df.iloc[1:4, -1] = 
1    3428000
2    8428000
3    4428000
Name: Salary, dtype: int64
df.iloc[1:4, -1].shape =  (3,)
df["Weight"] = 
0     75
1     74
2     70
3     80
4    100
5     72
6     85
Name: Weight, dtype: int64
df["Weight"].shape =  (7,)
df.loc[5] = 
Name       J.Root
Age            33
Weight         72
Salary    7028000
Name: 5, dtype: object
df.loc[5].shape =  (4,)
df.loc[1:5] = 
            Name  Age  Weight   Salary
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
df.loc[1:5].s

In [5]:
tenrand = torch.randn((1,2,3,4))
print("tenrand.shape = ", tenrand.shape)
print("tensorand = ")
print(tenrand)

tenrand = torch.randn((5,6,2,3))
print("tenrand.shape = ", tenrand.shape)
print("tensorand = ")
print(tenrand)

timeseries = torch.randn((5, 4, 1))
print("timeseries.shape = ", timeseries.shape)
print("timeseries = ")
print(timeseries)

timeseries = torch.randn((7, 5))
print("timeseries.shape = ", timeseries.shape)
print("timeseries = ")
print(timeseries)

timeseries = torch.randn((2, 3, 4))
print("timeseries.shape = ", timeseries.shape)
print("timeseries = ")
print(timeseries)
print("timeseries[:, -1, :] = ")
print(timeseries[:, -1, :])


tenrand.shape =  torch.Size([1, 2, 3, 4])
tensorand = 
tensor([[[[-1.1402,  0.5882, -1.3668, -0.3100],
          [ 0.4533, -0.1890, -0.4051,  2.5566],
          [-1.5427, -0.0879,  2.5263,  0.2424]],

         [[ 0.2157, -1.2202,  0.3058, -0.2494],
          [-1.1343, -0.4321, -0.9902,  0.4806],
          [-1.6206,  0.7853, -1.4102, -1.4673]]]])
tenrand.shape =  torch.Size([5, 6, 2, 3])
tensorand = 
tensor([[[[-1.4939, -0.9771, -1.0564],
          [ 0.3321,  0.7803, -0.3721]],

         [[-0.8353, -0.7052,  0.2465],
          [ 1.1595,  0.5438, -1.0344]],

         [[ 1.0698, -0.3154, -0.1786],
          [ 0.6853,  0.6297,  0.2737]],

         [[-0.1374,  0.1360, -1.2452],
          [-0.3056,  0.4820, -0.9033]],

         [[ 0.1100,  1.1174,  2.8117],
          [ 2.3133,  0.7486,  2.1605]],

         [[ 1.6158, -0.1887,  0.4493],
          [ 1.3663,  1.0136, -0.7267]]],


        [[[ 0.3744,  0.1187, -0.9487],
          [ 0.8417, -1.1984,  2.6501]],

         [[ 0.3554,  0.8298, -2.027

In [6]:
import torch.nn as nn

# Batch size = 4, Channel depth = 3, Height pixel number = 28 , Width pixel number = 28
input = torch.randn(4, 3, 28, 28)

# Targted for output height pixel number = 5 , width pixel number = 5
aapool = nn.AdaptiveAvgPool2d((5, 5))
output = aapool(input)
print("Input size:", input.shape)
print("Output size:", output.shape)

Input size: torch.Size([4, 3, 28, 28])
Output size: torch.Size([4, 3, 5, 5])


In [7]:
input = torch.randn(2, 3, 4, 4)
apool = nn.AdaptiveAvgPool2d((2, 2))
output = apool(input)
print("Input size:", input.shape)
print ("input = ")
print (input)
print("Output size:", output.shape)
print ("output = ")
print (output)

Input size: torch.Size([2, 3, 4, 4])
input = 
tensor([[[[ 0.2940, -1.2760,  0.5606, -0.5561],
          [-0.1927, -0.3372,  0.0551,  0.1918],
          [-1.0304,  0.8377, -0.8411, -0.5301],
          [-2.3650,  0.6384,  0.3592, -0.1666]],

         [[-0.3553, -1.0882, -0.2291,  0.9698],
          [-1.6196, -0.8834, -0.7170,  0.7841],
          [-0.6266,  0.5399,  1.4558,  1.2426],
          [ 0.7858, -1.2537, -1.4602,  0.1283]],

         [[-1.6421, -0.2507,  0.0638, -1.1044],
          [ 1.6973,  0.2304, -1.3022,  0.5001],
          [-1.3366, -0.3536,  1.1176,  1.0244],
          [-0.1889, -1.5625,  0.0172, -1.0148]]],


        [[[-0.5338, -0.9572, -1.3719, -1.4755],
          [-1.3618,  0.3130,  1.5208, -0.3849],
          [-0.6146,  0.0197, -1.3981, -0.6971],
          [ 0.2977,  1.6390,  0.9605, -0.4282]],

         [[ 2.1472, -1.4914,  0.3567,  0.2544],
          [ 0.5210, -0.4767, -2.6209,  0.5790],
          [-1.9009, -0.7035, -0.6571,  1.6291],
          [ 1.3321, -0.5265,  0.

In [8]:
input = torch.randn(2, 3, 4, 4)
ampool = nn.AdaptiveMaxPool2d((2, 2))
output = ampool(input)
print("Input size:", input.shape)
print("input = ")
print(input)
print("Output size:", output.shape)
print("output = ")
print(output)

Input size: torch.Size([2, 3, 4, 4])
input = 
tensor([[[[-1.0311, -0.5362,  1.5051,  0.0543],
          [ 0.0067, -0.3578,  0.7678, -0.4253],
          [-0.2732, -1.2893, -0.2589,  0.5384],
          [-1.6839, -0.3292, -1.0353, -0.7360]],

         [[ 0.2451, -0.9870, -0.8112, -0.3590],
          [ 0.4468, -0.1037, -0.7983,  1.9580],
          [ 0.9734, -0.3533, -1.0785,  0.0702],
          [-0.6550, -0.6986, -0.5989,  0.7397]],

         [[ 1.0538, -0.2315, -0.7444,  0.4612],
          [ 0.4302,  0.7692,  0.0325,  2.2053],
          [-0.0755, -1.5305, -0.1875,  2.2941],
          [-2.4426, -0.3495,  0.5190,  0.9112]]],


        [[[-1.3506, -0.5614,  0.5859,  2.4194],
          [-1.5383,  0.1463, -0.5751, -0.6656],
          [ 1.3160, -0.3122,  0.1215,  0.1576],
          [ 0.2177, -0.1611, -0.7275, -1.5692]],

         [[-0.3960, -1.1726,  0.7259, -0.2367],
          [-0.5314, -0.2779, -0.5269, -0.7346],
          [ 0.2604, -1.8894, -0.5844,  1.2575],
          [-0.1204, -0.3202, -2.