<a href="https://colab.research.google.com/github/snpsuen/Deep_Learning_Data/blob/main/script/pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd

In [ ]:
# Initializing the nested list with Data set
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

# creating a pandas dataframe
df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print("df = ")
print(df) # data frame before slicing
print("df.shape = ", df.shape) # data frame before slicing
print("df.iloc[1,2] = ", df.iloc[1,2])
print("df.iloc[1:4, -1] = ")
print(df.iloc[1:4, -1])
print("df.iloc[1:4, -1].shape = ", df.iloc[1:4, -1].shape)
print("df[\"Weight\"] = ")
print(df["Weight"])
print("df[\"Weight\"].shape = ", df["Weight"].shape)
print("df.loc[5] = ")
print(df.loc[5])
print("df.loc[5].shape = ", df.loc[5].shape)
print("df.loc[1:5] = ")
print(df.loc[1:5])
print("df.loc[1:5].shape = ", df.loc[1:5].shape)
df_weight = df["Weight"].values.reshape(-1, 1)
print("df_weight type = ", type(df_weight.shape))
print("df_weight.shape = ", df_weight.shape)
print("df_weight = ")
print(df_weight)

df = 
            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000
df.shape =  (7, 4)
df.iloc[1,2] =  74
df.iloc[1:4, -1] = 
1    3428000
2    8428000
3    4428000
Name: Salary, dtype: int64
df.iloc[1:4, -1].shape =  (3,)
df["Weight"] = 
0     75
1     74
2     70
3     80
4    100
5     72
6     85
Name: Weight, dtype: int64
df["Weight"].shape =  (7,)
df.loc[5] = 
Name       J.Root
Age            33
Weight         72
Salary    7028000
Name: 5, dtype: object
df.loc[5].shape =  (4,)
df.loc[1:5] = 
            Name  Age  Weight   Salary
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
df.loc[1:5].s

In [ ]:
tenrand = torch.randn((1,2,3,4))
print("tenrand.shape = ", tenrand.shape)
print("tensorand = ")
print(tenrand)

timeseries = torch.randn((5, 4, 1))
print("timeseries.shape = ", timeseries.shape)
print("timeseries = ")
print(timeseries)

timeseries = torch.randn((7, 5))
print("timeseries.shape = ", timeseries.shape)
print("timeseries = ")
print(timeseries)

timeseries = torch.randn((2, 3, 4))
print("timeseries.shape = ", timeseries.shape)
print("timeseries = ")
print(timeseries)
print("timeseries[:, -1, :] = ")
print(timeseries[:, -1, :])


tenrand.shape =  torch.Size([1, 2, 3, 4])
tensorand = 
tensor([[[[-3.9541e-01, -3.1831e-02,  7.9321e-01, -1.9636e-01],
          [ 9.7644e-01,  6.0231e-01, -5.6331e-01, -3.3942e-01],
          [-2.1515e-01,  3.6406e-01, -1.9803e+00, -2.8816e-01]],

         [[ 7.5726e-01, -3.6563e-01, -6.0421e-01,  1.4058e+00],
          [-8.1480e-01, -3.4860e-01,  1.6913e+00,  1.2646e-03],
          [ 1.1294e+00,  5.2725e-01, -1.4075e+00,  4.1270e-01]]]])
timeseries.shape =  torch.Size([5, 4, 1])
timeseries = 
tensor([[[ 0.2234],
         [-0.9372],
         [-0.1228],
         [-0.8656]],

        [[-0.1325],
         [ 0.7211],
         [ 1.1865],
         [-1.3329]],

        [[-0.7214],
         [-1.1662],
         [-0.0925],
         [ 0.8107]],

        [[-0.0552],
         [-0.7269],
         [ 1.9000],
         [ 1.2182]],

        [[ 0.3807],
         [-1.3056],
         [ 0.3784],
         [-0.5752]]])
timeseries.shape =  torch.Size([7, 5])
timeseries = 
tensor([[-0.5814,  0.7935, -0.4339,  

In [ ]:
import torch.nn as nn

# Batch size = 4, Channel depth = 3, Height pixel number = 28 , Width pixel number = 28
input = torch.randn(4, 3, 28, 28)

# Targted for output height pixel number = 5 , width pixel number = 5
aapool = nn.AdaptiveAvgPool2d((5, 5))
output = aapool(input)
print("Input size:", input.shape)
print("Output size:", output.shape)

Input size: torch.Size([4, 3, 28, 28])
Output size: torch.Size([4, 3, 5, 5])


In [ ]:
input = torch.randn(2, 3, 4, 4)
apool = nn.AdaptiveAvgPool2d((2, 2))
output = apool(input)
print("Input size:", input.shape)
print ("input = ")
print (input)
print("Output size:", output.shape)
print ("output = ")
print (output)

Input size: torch.Size([2, 3, 4, 4])
input = 
tensor([[[[ 0.7402, -0.3017, -0.8718,  1.7972],
          [ 1.3465, -0.6403,  0.6707,  1.3998],
          [ 1.8476,  0.6210,  2.2221, -0.7551],
          [-0.3642, -0.3877,  1.3109, -0.4864]],

         [[-0.8821,  0.8965, -1.5119, -1.0204],
          [-1.3951, -1.9064,  0.0149,  0.6144],
          [-0.1216, -1.0375, -0.3479, -0.4708],
          [-0.4151, -0.3886,  0.2075,  0.5234]],

         [[-1.2403, -0.0114,  1.0724, -0.0848],
          [-0.1619, -0.8968,  1.2232,  0.2989],
          [ 1.0623, -0.3994,  1.4847,  1.4419],
          [-1.1213,  2.7476,  0.9469,  0.5783]]],


        [[[-0.6234,  0.3551, -0.4497,  0.2220],
          [-0.2099, -1.3281,  1.6052,  0.4037],
          [-1.6348, -1.7073,  2.0141, -0.3546],
          [-1.8267, -0.2032,  0.0993,  0.2665]],

         [[ 1.0979,  1.5328, -0.4804,  1.4254],
          [-0.3731, -1.0780, -0.7068,  0.6561],
          [ 0.5912,  1.0715, -1.1533,  0.6214],
          [ 0.0241, -0.0553, -1.

In [ ]:
input = torch.randn(2, 3, 4, 4)
ampool = nn.AdaptiveMaxPool2d((2, 2))
output = ampool(input)
print("Input size:", input.shape)
print("input = ")
print(input)
print("Output size:", output.shape)
print("output = ")
print(output)

Input size: torch.Size([2, 3, 4, 4])
input = 
tensor([[[[ 0.9565,  0.6426,  0.8628, -0.9974],
          [-0.9997,  1.0540,  1.6085,  1.4973],
          [ 0.1855,  0.6583, -0.6347, -0.4459],
          [-0.4817,  0.7899, -0.8081, -0.3242]],

         [[ 1.7273,  0.1410,  1.2217,  1.5502],
          [ 0.2866,  0.1459, -0.7480,  1.2656],
          [ 0.4870, -0.9406, -0.8528,  0.1662],
          [ 0.5025,  0.2308, -1.1219,  1.3817]],

         [[-0.1648, -0.5748,  0.1158, -1.4456],
          [ 1.6752, -0.9980, -0.6083, -0.5766],
          [ 0.3753,  1.8761, -0.3326,  0.8525],
          [-0.8516,  0.0472,  0.3284, -1.7723]]],


        [[[ 0.1988,  0.1214, -1.2587,  0.8269],
          [ 0.6346, -0.5131,  0.7331,  2.7048],
          [-1.4852,  1.1846,  1.1674, -0.1521],
          [-0.6560, -1.3812,  0.2106,  0.6720]],

         [[ 0.6054, -1.7214,  1.4283,  1.4220],
          [-0.5423, -1.0364,  0.9938,  0.1923],
          [-0.8702,  0.9663, -0.3929, -0.4316],
          [ 0.6359, -1.1034, -2.